#include <raylib.h>

#include <string>

#include "Lib/FontParser/Bdf.h"

namespace Assets {
Font cozette;
Texture2D CursorDefault;
Texture2D WindowCloseButtonX;
Texture2D IconAdd;
Texture2D IconAddDirectory;
Texture2D IconAddFile;
Texture2D IconApplicationAIChat;
Texture2D IconApplicationGeminataMediaPlayer;
Texture2D IconApplicationGeminiBrowser;
Texture2D IconApplicationGonsole;
Texture2D IconApplicationHallucinationBox;
Texture2D IconApplicationHermitTracker;
Texture2D IconApplicationInkSpot;
Texture2D IconApplicationMIDISynth;
Texture2D IconApplicationShadowBg;
Texture2D IconArrowDown;
Texture2D IconArrowUp;
Texture2D IconAssistant;
Texture2D IconBackward;
Texture2D IconBackwardSmall;
Texture2D IconBook;
Texture2D IconBookmarkAdd;
Texture2D IconBookmarkContour;
Texture2D IconBookOpen;
Texture2D IconBurn;
Texture2D IconCharge;
Texture2D IconCheck;
Texture2D IconChevronClosed;
Texture2D IconChevronOpen;
Texture2D IconDelete;
Texture2D IconDialogError32;
Texture2D IconDialogInfo32;
Texture2D IconDialogQuestion32;
Texture2D IconDialogWarning32;
Texture2D IconDownload;
Texture2D IconDropdownArrow;
Texture2D IconEdit;
Texture2D IconEye;
Texture2D IconEyeTired;
Texture2D IconFastForward;
Texture2D IconFileTypeDirectory;
Texture2D IconFileTypeDirectory32;
Texture2D IconFileTypeImage;
Texture2D IconFileTypeImage32;
Texture2D IconFileTypeSound;
Texture2D IconFileTypeSound32;
Texture2D IconFileTypeUnknown;
Texture2D IconFileTypeUnknown32;
Texture2D IconForward;
Texture2D IconGenerate;
Texture2D IconGraph;
Texture2D IconHome;
Texture2D IconIdea;
Texture2D IconLockLocked;
Texture2D IconLockUnlocked;
Texture2D IconNotRepeatPlaylist;
Texture2D IconOpenExternal;
Texture2D IconPause;
Texture2D IconPlay;
Texture2D IconPlayerNextTrack;
Texture2D IconPlayerPreviousTrack;
Texture2D IconQuestion;
Texture2D IconRadioButtonFilled;
Texture2D IconReasoning;
Texture2D IconReasoningDisabled;
Texture2D IconRefresh;
Texture2D IconRename;
Texture2D IconRepeatCurrentTrack;
Texture2D IconRepeatPlaylist;
Texture2D IconReset;
Texture2D IconSave;
Texture2D IconSearch;
Texture2D IconSend;
Texture2D IconSettings;
Texture2D IconShufflePlaylist;
Texture2D IconSpinnerArrow;
Texture2D IconStatusBatteryA;
Texture2D IconStatusBatteryB;
Texture2D IconStatusBatteryC;
Texture2D IconStatusBatteryD;
Texture2D IconStatusBatteryE;
Texture2D IconStatusBatteryF;
Texture2D IconStatusBatteryG;
Texture2D IconStatusBatteryH;
Texture2D IconStatusBatteryI;
Texture2D IconStatusBatteryJ;
Texture2D IconStop;
Texture2D IconTabClose;
Texture2D IconTableView;
Texture2D IconTiledView;
Texture2D IconTreeviewBranch1;
Texture2D IconTreeviewBranch2;
Texture2D IconWindowClose;
Texture2D IconWindowMaximize;
Texture2D IconWindowMinimize;
Texture2D IconWindowPinned;
Texture2D IconWindowRestore;
Texture2D IconWindowUnpinned;

void Initialize() {
    cozette = LoadFontBDF("Assets/cozette.bdf");
    CursorDefault = LoadTexture("Assets/CursorDefault.png");
    WindowCloseButtonX = LoadTexture("Assets/WindowCloseButtonX.png");
    IconAdd = LoadTexture("Assets/Icons/Add.png");
    IconAddDirectory = LoadTexture("Assets/Icons/AddDirectory.png");
    IconAddFile = LoadTexture("Assets/Icons/AddFile.png");
    IconApplicationAIChat = LoadTexture("Assets/Icons/ApplicationAIChat.png");
    IconApplicationGeminataMediaPlayer =
        LoadTexture("Assets/Icons/ApplicationGeminataMediaPlayer.png");
    IconApplicationGeminiBrowser =
        LoadTexture("Assets/Icons/ApplicationGeminiBrowser.png");
    IconApplicationGonsole = LoadTexture("Assets/Icons/ApplicationGonsole.png");
    IconApplicationHallucinationBox =
        LoadTexture("Assets/Icons/ApplicationHallucinationBox.png");
    IconApplicationHermitTracker =
        LoadTexture("Assets/Icons/ApplicationHermitTracker.png");
    IconApplicationInkSpot = LoadTexture("Assets/Icons/ApplicationInkSpot.png");
    IconApplicationMIDISynth =
        LoadTexture("Assets/Icons/ApplicationMIDISynth.png");
    IconApplicationShadowBg =
        LoadTexture("Assets/Icons/ApplicationShadowBg.png");
    IconArrowDown = LoadTexture("Assets/Icons/ArrowDown.png");
    IconArrowUp = LoadTexture("Assets/Icons/ArrowUp.png");
    IconAssistant = LoadTexture("Assets/Icons/Assistant.png");
    IconBackward = LoadTexture("Assets/Icons/Backward.png");
    IconBackwardSmall = LoadTexture("Assets/Icons/BackwardSmall.png");
    IconBook = LoadTexture("Assets/Icons/Book.png");
    IconBookmarkAdd = LoadTexture("Assets/Icons/BookmarkAdd.png");
    IconBookmarkContour = LoadTexture("Assets/Icons/BookmarkContour.png");
    IconBookOpen = LoadTexture("Assets/Icons/BookOpen.png");
    IconBurn = LoadTexture("Assets/Icons/Burn.png");
    IconCharge = LoadTexture("Assets/Icons/Charge.png");
    IconCheck = LoadTexture("Assets/Icons/Check.png");
    IconChevronClosed = LoadTexture("Assets/Icons/ChevronClosed.png");
    IconChevronOpen = LoadTexture("Assets/Icons/ChevronOpen.png");
    IconDelete = LoadTexture("Assets/Icons/Delete.png");
    IconDialogError32 = LoadTexture("Assets/Icons/DialogError32.png");
    IconDialogInfo32 = LoadTexture("Assets/Icons/DialogInfo32.png");
    IconDialogQuestion32 = LoadTexture("Assets/Icons/DialogQuestion32.png");
    IconDialogWarning32 = LoadTexture("Assets/Icons/DialogWarning32.png");
    IconDownload = LoadTexture("Assets/Icons/Download.png");
    IconDropdownArrow = LoadTexture("Assets/Icons/DropdownArrow.png");
    IconEdit = LoadTexture("Assets/Icons/Edit.png");
    IconEye = LoadTexture("Assets/Icons/Eye.png");
    IconEyeTired = LoadTexture("Assets/Icons/EyeTired.png");
    IconFastForward = LoadTexture("Assets/Icons/FastForward.png");
    IconFileTypeDirectory = LoadTexture("Assets/Icons/FileTypeDirectory.png");
    IconFileTypeDirectory32 =
        LoadTexture("Assets/Icons/FileTypeDirectory32.png");
    IconFileTypeImage = LoadTexture("Assets/Icons/FileTypeImage.png");
    IconFileTypeImage32 = LoadTexture("Assets/Icons/FileTypeImage32.png");
    IconFileTypeSound = LoadTexture("Assets/Icons/FileTypeSound.png");
    IconFileTypeSound32 = LoadTexture("Assets/Icons/FileTypeSound32.png");
    IconFileTypeUnknown = LoadTexture("Assets/Icons/FileTypeUnknown.png");
    IconFileTypeUnknown32 = LoadTexture("Assets/Icons/FileTypeUnknown32.png");
    IconForward = LoadTexture("Assets/Icons/Forward.png");
    IconGenerate = LoadTexture("Assets/Icons/Generate.png");
    IconGraph = LoadTexture("Assets/Icons/Graph.png");
    IconHome = LoadTexture("Assets/Icons/Home.png");
    IconIdea = LoadTexture("Assets/Icons/Idea.png");
    IconLockLocked = LoadTexture("Assets/Icons/LockLocked.png");
    IconLockUnlocked = LoadTexture("Assets/Icons/LockUnlocked.png");
    IconNotRepeatPlaylist = LoadTexture("Assets/Icons/NotRepeatPlaylist.png");
    IconOpenExternal = LoadTexture("Assets/Icons/OpenExternal.png");
    IconPause = LoadTexture("Assets/Icons/Pause.png");
    IconPlay = LoadTexture("Assets/Icons/Play.png");
    IconPlayerNextTrack = LoadTexture("Assets/Icons/PlayerNextTrack.png");
    IconPlayerPreviousTrack =
        LoadTexture("Assets/Icons/PlayerPreviousTrack.png");
    IconQuestion = LoadTexture("Assets/Icons/Question.png");
    IconRadioButtonFilled = LoadTexture("Assets/Icons/RadioButtonFilled.png");
    IconReasoning = LoadTexture("Assets/Icons/Reasoning.png");
    IconReasoningDisabled = LoadTexture("Assets/Icons/ReasoningDisabled.png");
    IconRefresh = LoadTexture("Assets/Icons/Refresh.png");
    IconRename = LoadTexture("Assets/Icons/Rename.png");
    IconRepeatCurrentTrack = LoadTexture("Assets/Icons/RepeatCurrentTrack.png");
    IconRepeatPlaylist = LoadTexture("Assets/Icons/RepeatPlaylist.png");
    IconReset = LoadTexture("Assets/Icons/Reset.png");
    IconSave = LoadTexture("Assets/Icons/Save.png");
    IconSearch = LoadTexture("Assets/Icons/Search.png");
    IconSend = LoadTexture("Assets/Icons/Send.png");
    IconSettings = LoadTexture("Assets/Icons/Settings.png");
    IconShufflePlaylist = LoadTexture("Assets/Icons/ShufflePlaylist.png");
    IconSpinnerArrow = LoadTexture("Assets/Icons/SpinnerArrow.png");
    IconStatusBatteryA = LoadTexture("Assets/Icons/StatusBatteryA.png");
    IconStatusBatteryB = LoadTexture("Assets/Icons/StatusBatteryB.png");
    IconStatusBatteryC = LoadTexture("Assets/Icons/StatusBatteryC.png");
    IconStatusBatteryD = LoadTexture("Assets/Icons/StatusBatteryD.png");
    IconStatusBatteryE = LoadTexture("Assets/Icons/StatusBatteryE.png");
    IconStatusBatteryF = LoadTexture("Assets/Icons/StatusBatteryF.png");
    IconStatusBatteryG = LoadTexture("Assets/Icons/StatusBatteryG.png");
    IconStatusBatteryH = LoadTexture("Assets/Icons/StatusBatteryH.png");
    IconStatusBatteryI = LoadTexture("Assets/Icons/StatusBatteryI.png");
    IconStatusBatteryJ = LoadTexture("Assets/Icons/StatusBatteryJ.png");
    IconStop = LoadTexture("Assets/Icons/Stop.png");
    IconTabClose = LoadTexture("Assets/Icons/TabClose.png");
    IconTableView = LoadTexture("Assets/Icons/TableView.png");
    IconTiledView = LoadTexture("Assets/Icons/TiledView.png");
    IconTreeviewBranch1 = LoadTexture("Assets/Icons/TreeviewBranch1.png");
    IconTreeviewBranch2 = LoadTexture("Assets/Icons/TreeviewBranch2.png");
    IconWindowClose = LoadTexture("Assets/Icons/WindowClose.png");
    IconWindowMaximize = LoadTexture("Assets/Icons/WindowMaximize.png");
    IconWindowMinimize = LoadTexture("Assets/Icons/WindowMinimize.png");
    IconWindowPinned = LoadTexture("Assets/Icons/WindowPinned.png");
    IconWindowRestore = LoadTexture("Assets/Icons/WindowRestore.png");
    IconWindowUnpinned = LoadTexture("Assets/Icons/WindowUnpinned.png");
}

void Cleanup() {
    UnloadTexture(IconAdd);
    UnloadTexture(IconAddDirectory);
    UnloadTexture(IconAddFile);
    UnloadTexture(IconApplicationAIChat);
    UnloadTexture(IconApplicationGeminataMediaPlayer);
    UnloadTexture(IconApplicationGeminiBrowser);
    UnloadTexture(IconApplicationGonsole);
    UnloadTexture(IconApplicationHallucinationBox);
    UnloadTexture(IconApplicationHermitTracker);
    UnloadTexture(IconApplicationInkSpot);
    UnloadTexture(IconApplicationMIDISynth);
    UnloadTexture(IconApplicationShadowBg);
    UnloadTexture(IconArrowDown);
    UnloadTexture(IconArrowUp);
    UnloadTexture(IconAssistant);
    UnloadTexture(IconBackward);
    UnloadTexture(IconBackwardSmall);
    UnloadTexture(IconBook);
    UnloadTexture(IconBookmarkAdd);
    UnloadTexture(IconBookmarkContour);
    UnloadTexture(IconBookOpen);
    UnloadTexture(IconBurn);
    UnloadTexture(IconCharge);
    UnloadTexture(IconCheck);
    UnloadTexture(IconChevronClosed);
    UnloadTexture(IconChevronOpen);
    UnloadTexture(IconDelete);
    UnloadTexture(IconDialogError32);
    UnloadTexture(IconDialogInfo32);
    UnloadTexture(IconDialogQuestion32);
    UnloadTexture(IconDialogWarning32);
    UnloadTexture(IconDownload);
    UnloadTexture(IconDropdownArrow);
    UnloadTexture(IconEdit);
    UnloadTexture(IconEye);
    UnloadTexture(IconEyeTired);
    UnloadTexture(IconFastForward);
    UnloadTexture(IconFileTypeDirectory);
    UnloadTexture(IconFileTypeDirectory32);
    UnloadTexture(IconFileTypeImage);
    UnloadTexture(IconFileTypeImage32);
    UnloadTexture(IconFileTypeSound);
    UnloadTexture(IconFileTypeSound32);
    UnloadTexture(IconFileTypeUnknown);
    UnloadTexture(IconFileTypeUnknown32);
    UnloadTexture(IconForward);
    UnloadTexture(IconGenerate);
    UnloadTexture(IconGraph);
    UnloadTexture(IconHome);
    UnloadTexture(IconIdea);
    UnloadTexture(IconLockLocked);
    UnloadTexture(IconLockUnlocked);
    UnloadTexture(IconNotRepeatPlaylist);
    UnloadTexture(IconOpenExternal);
    UnloadTexture(IconPause);
    UnloadTexture(IconPlay);
    UnloadTexture(IconPlayerNextTrack);
    UnloadTexture(IconPlayerPreviousTrack);
    UnloadTexture(IconQuestion);
    UnloadTexture(IconRadioButtonFilled);
    UnloadTexture(IconReasoning);
    UnloadTexture(IconReasoningDisabled);
    UnloadTexture(IconRefresh);
    UnloadTexture(IconRename);
    UnloadTexture(IconRepeatCurrentTrack);
    UnloadTexture(IconRepeatPlaylist);
    UnloadTexture(IconReset);
    UnloadTexture(IconSave);
    UnloadTexture(IconSearch);
    UnloadTexture(IconSend);
    UnloadTexture(IconSettings);
    UnloadTexture(IconShufflePlaylist);
    UnloadTexture(IconSpinnerArrow);
    UnloadTexture(IconStatusBatteryA);
    UnloadTexture(IconStatusBatteryB);
    UnloadTexture(IconStatusBatteryC);
    UnloadTexture(IconStatusBatteryD);
    UnloadTexture(IconStatusBatteryE);
    UnloadTexture(IconStatusBatteryF);
    UnloadTexture(IconStatusBatteryG);
    UnloadTexture(IconStatusBatteryH);
    UnloadTexture(IconStatusBatteryI);
    UnloadTexture(IconStatusBatteryJ);
    UnloadTexture(IconStop);
    UnloadTexture(IconTabClose);
    UnloadTexture(IconTableView);
    UnloadTexture(IconTiledView);
    UnloadTexture(IconTreeviewBranch1);
    UnloadTexture(IconTreeviewBranch2);
    UnloadTexture(IconWindowClose);
    UnloadTexture(IconWindowMaximize);
    UnloadTexture(IconWindowMinimize);
    UnloadTexture(IconWindowPinned);
    UnloadTexture(IconWindowRestore);
    UnloadTexture(IconWindowUnpinned);
    UnloadTexture(WindowCloseButtonX);
    UnloadTexture(CursorDefault);
    UnloadFont(cozette);
}
}  // namespace Assets
